config/routes.rb
Rails.application.routes.draw do
  get 'images/index'

  get 'images/create'

  devise_for :penggunas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'home#index'
  get '/', to: 'home#index'
  get '/tes', to: 'home#tes'
  get '/detail', to: 'kosts#detail'
  get '/inbox', to: 'kosts#inbox'
  get '/outbox', to: 'kosts#outbox'
  resources :kosts
  resources :messages
  resources :images, only: [:index, :create]
end

app/models/kost.rb
class Kost < ApplicationRecord

	belongs_to :pengguna, optional:true
	has_many :image

	has_attached_file :kost_img, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :kost_img, :content_type => /\Aimage\/.*\Z/

	has_attached_file :kost_img2, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :kost_img2, :content_type => /\Aimage\/.*\Z/

	has_attached_file :kost_img3, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :kost_img3, :content_type => /\Aimage\/.*\Z/
end

app/controllers/kosts_controller.rb
class KostsController < ApplicationController
	before_action :set_kost, only: [:show, :edit, :update, :destroy]

	layout 'dashboard', except: [:detail, :show]
	before_action :authenticate_pengguna!, except: [:detail, :show]

	def index
		@pengguna = Pengguna.find(current_pengguna.id)
		@kosts = Kost.where(pengguna: current_pengguna.id)
	end

	def detail
		if params[:search]
			@kosts = Kost.where("kosts.alamat LIKE concat('%', ?, '%')", params[:search])
		else
			@kosts = Kost.all
		end
	end

	def show
		@kost = Kost.find(params[:id])
	end

	def inbox
		@pengguna = Pengguna.find(current_pengguna.id)
		@message = Message.find_by_sql(
		["SELECT messages.id as id, messages.pengguna_id as sender, kosts.nama_kos, messages.pesan, receiver,penggunas.email, kost_id
			FROM ((messages INNER JOIN kosts ON messages.kost_id = kosts.id)
			INNER JOIN penggunas ON kosts.pengguna_id = penggunas.id) WHERE messages.receiver = ?", current_pengguna.id])
	end

	def outbox
		@pengguna = Pengguna.find(current_pengguna.id)
		@message = Message.find_by_sql(
		["SELECT  messages.id as id, messages.pengguna_id as sender, kosts.nama_kos, messages.pesan, receiver,penggunas.email, kost_id
			FROM ((messages INNER JOIN kosts ON messages.kost_id = kosts.id)
			INNER JOIN penggunas ON kosts.pengguna_id = penggunas.id) WHERE messages.pengguna_id = ?", current_pengguna.id])
	end

	def new
		@pengguna = Pengguna.find(current_pengguna.id)
		@kost = Kost.new
	end

	def create
		@pengguna = Pengguna.find(current_pengguna.id)
		@kost = Kost.new(resource_params)
		if @kost.save
			redirect_to controller: 'kosts', action: 'index'
		else
			render plain: 'gagal'
		end
	end


	def edit
		@kost = Kost.find(params[:id])
	end

	def update
		@kost = Kost.find(params[:id])
		@kost.update(resource_params)
		redirect_to controller: 'kosts', action: 'index'
	end

	def destroy
		kost = Kost.find(params[:id])
		kost.destroy
		redirect_to controller: 'kosts', action: 'index'
	end


	private

	def set_kost
		@kost = Kost.find(params[:id])
	end


	def resource_params
		params.require(:kost).permit(:nama_kos, :harga_kos, :fasilitas, :alamat, :keterangan_lain, :pengguna_id, :kost_img, :kost_img2, :kost_img3)
	end

end

app/views/kosts/_footer.html.erb
<div class="row widget-footer">
  <div class="container">
    <div class="col-md-4">
      <h2>Layanan Pelanggan</h2><br />
        <h4><i class="fa fa-whatsapp" aria-hidden="true"></i> +0857-2474-8508</h4>
        <h4>info@lapakos.com</h4>
    </div>
    <div class="col-md-4">
      <h2>Stay Connected</h2>
      <div id="iconsosmed">
        <a href="#" class="fa fa-facebook"></a>
        <a href="#" class="fa fa-instagram"></a>
        <a href="#" class="fa fa-youtube"></a>
        <a href="#" class="fa fa-twitter"></a>
      </div>
    </div>
    <div class="col-md-4">
      <h2>Download Apps</h2>
      <%= image_tag("playstore.png", :alt => "play-store", :class => "play-store") %><br/>
      <%= image_tag("applestore.png", :alt => "play-store", :class => "play-store") %>
    </div>

  </div><!--end container-->
</div><!--end row-->


<footer>
  <p>LapaKos &copy; 2017</p>
</footer>

app/views/kosts/_form.html.erb
<%= form_for @kost, class: "form-horizontal" do |f| %>

	<div class="form-group">
		<%= f.label :'Nama Kos: ', class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_field :nama_kos, class: "form-control", placeholder: "Kosan Munggaran" %>
		</div>
	</div>
	</br>	</br>	</br>

	<div class="form-group">
		<%= f.label :'Harga Kos: ', class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_field :harga_kos, class: "form-control", placeholder: "5000000" %>
		</div>
	</div>
	</br>	</br>

	<div class="form-group">
		<%= f.label :'Fasilitas: ', class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_area :fasilitas, class: "form-control", placeholder: "WC di dalam, AC, Dapur"  %>
		</div>
	</div>
	</br>	</br>	</br>

	<div class="form-group">
		<%= f.label :'Alamat: ', class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_area :alamat, class: "form-control", placeholder: "alamat lengkap beserta kota"  %>
		</div>
	</div>
	</br>	</br>	</br>

	<div class="form-group">
		<%= f.label :'Keterangan Lain: ', class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_area :keterangan_lain, class: "form-control", placeholder: "15 menit ke kampus UIN Bandung" %>
		</div>
	</div>
	</br>	</br>	</br>

	<div class="form-group">
		<%= f.label :'Upload Photos: ', class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<div>
				<%= f.file_field :kost_img, class: "btn btn-default" %></br>
				<%= f.file_field :kost_img2, class: "btn btn-default" %></br>
				<%= f.file_field :kost_img3, class: "btn btn-default" %></br>
			</div>
		</div>
	</div>
	</br>	</br>	</br>

	<%= f.hidden_field :pengguna_id, :value => current_pengguna.id %>
	
	<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
			<%= f.submit 'Submit', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/kosts/_header.html.erb
<!--header-->
<header>
  <div class="wrapper-header container">
    <!--logo-->
    <div id="logo">
      <a href="/">
        <%= image_tag("logo.png", :alt => "LapaKos") %>
      </a>
    </div>
    <!--end of logo-->
    <!--nav-->
    <nav>
      <ul>
        <li><%= link_to "Login", kosts_path %></li>
        <li><%= link_to "Sign Up", new_pengguna_registration_path	 %></li>
        <li><%= link_to "Kelola Kosan", new_pengguna_registration_path, class: "btkelola"%></li>
      </ul>
    </nav>
    <!--end of nav-->
  </div>
</header>
<!--end of header-->

app/views/kosts/_searchbox.html.erb
<div class="search-detail-wrapper">
  <div class="form-group">
      <div>
        <%= form_tag detail_path, class: "searchwrapper", :method => "get" do %>
            <%= text_field_tag :search, params[:search], class: "form-control", class: "search-detail", placeholder: "ketik alamat kosan" %>
              <%= submit_tag "CARI", :name => nil, class: "btn btn-search float-right" %>
        <% end %>
      </div>
    </div>
</div>

app/views/kosts/detail.html.erb
<%= render 'header' %>
<%= render 'searchbox'%>

<div class="container">
	<div class="col-sm-9 content-detail">
		<% @kosts.each do |b| %>
			<div class="detail-box">
				<div class="box-img"><%= image_tag b.kost_img.url(:medium)%></div>
				<div class="box-nama"><h3><%= b.nama_kos %></h2></div>
				<div class="box-harga"><h3>IDR <%= b.harga_kos %><h3></div>
				<div class="box-alamat"><p><%= b.alamat %></p></div>
				<div class="box-pesan"><p><%= link_to 'PESAN', {controller: 'kosts', action:'show', id: b.id},  class: 'btn-pesan' %></p></div>
			</div>
		<% end %>
	</div>

	<div class="col-sm-3 sidebar-detail">

		<div class="sidebar-part">
			<div class="side-title">
				<p>Harga</p>
			</div>
			<div class="side-content">
				content
			</div>
		</div>

		<div class="sidebar-part">
			<div class="side-title">
				<p>Harga</p>
			</div>
			<div class="side-content">
				content
			</div>
		</div>

		<div class="sidebar-part">
			<div class="side-title">
				<p>Harga</p>
			</div>
			<div class="side-content">
				content
			</div>
		</div>

	</div>

</div>

</div>

<br/>
<%= render 'footer'%>

app/views/kosts/edit.html.erb
<div class="judul-dashboard">
	<h1>Edit Kosan</h1>
</div>

<%= render 'form'%>

app/views/kosts/inbox.html.erb
<h1>inbox:</h1>
<% @message.each do |m| %>
		<div class="msg msg--them">
				<blockquote>
					<div>lapak: <%= m.nama_kos %></div>
					<div><%= m.pesan %></div>
					<div>from: <%= m.email %></div>
					<%= link_to 'delete', {controller: 'messages', action:'destroy', id: m.id}, method: :delete, class: 'btn btn-danger' %>
					<%= link_to 'reply', {controller: 'messages', action:'new',
					:received => m.sender, :param_id_kos => m.kost_id }, class: 'btn btn-primary' %>
				</blockquote>
		</div>
<% end %>

app/views/kosts/index.html (copy).erb
<h1>Daftar Kosan:</h1>
<% @kosts.each do |b| %>
	<div>
		<div><%= b.id %></div>
		<div><%= b.nama_kos %></div>
		<div><%= b.harga_kos %></div>
		<div><%= b.fasilitas %></div>
		<div><%= b.alamat %></div>
		<div><%= b.keterangan_lain %></div>
		<div><%= link_to 'show', {controller: 'kosts', action:'show', id: b.id} %></div>
		<div><%= link_to 'edit', {controller: 'kosts', action:'edit', id: b.id} %></div>
		<div><%= link_to 'delete', {controller: 'kosts', action:'destroy', id: b.id}, method: :delete %></div>
		<br>
	</div>
<% end %>

app/views/kosts/index.html.erb
<div class="judul-dashboard">
  <h1>Lapak Kosan Anda:</h1>
</div>

<div class="col-sm-12 content-detail">
  <% @kosts.each do |b| %>
    <div class="detail-box">
      <div class="box-img"><%= image_tag b.kost_img.url(:medium)%></div>
      <div class="box-nama"><h3><%= b.nama_kos %></h2></div>
      <div class="box-harga"><h3>IDR <%= b.harga_kos %><h3></div>
      <div class="box-alamat"><p><%= b.alamat %></p></div>
      <div class="box-action">
          <%= link_to 'edit', {controller: 'kosts', action:'edit', id: b.id},  class: "btn btn-info" %>
          <%= link_to 'delete', {controller: 'kosts', action:'destroy', id: b.id}, method: :delete, class: "btn btn-danger" %>
      </div>

    </div>
  <% end %>
</div>

app/views/kosts/new.html.erb
<div class="judul-dashboard">
	<h1>Tambah Kosan</h1>
</div>
<% if @kost.errors.any? %>
	<div>
		<% @kost.errors.full_messages.each do |message| %>
			<div><% message %></div><br>
		<% end %>
	</div>
<% end %>

<%= render 'form'%>

app/views/kosts/outbox.html.erb
<h1>outbox:</h1>
<% @message.each do |m| %>
<div class="msg msg--me">
		<blockquote>
			<div>lapak:<%= m.nama_kos %></div>
			<div><%= m.pesan %></div>
			<div>to: <%= m.email %></div>
			<br>
			<%= link_to 'delete', {controller: 'messages', action:'destroy', id: m.id}, method: :delete, class: 'btn btn-danger' %>
		</blockquote>
</div>

<% end %>

app/views/kosts/show.html.erb
<%= render 'header' %>
<%= render 'searchbox'%>
<div class="container">
  <div class="carousel carousel-show slide article-slide" id="article-photo-carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner cont-slider">

      <div class="item active">
        <%= image_tag @kost.kost_img.url(:original), class: "show-img", style: "height:440px;"%>
      </div>
      <div class="item">
        <%= image_tag @kost.kost_img2.url(:original), class: "show-img", style: "height:440px;"%>
      </div>
      <div class="item">
        <%= image_tag @kost.kost_img3.url(:original), class: "show-img", style: "height:440px;"%>
      </div>
    </div>
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li class="active" data-slide-to="0" data-target="#article-photo-carousel">
        <%= image_tag @kost.kost_img.url(:original)%>
      </li>
      <li class="" data-slide-to="1" data-target="#article-photo-carousel">
        <%= image_tag @kost.kost_img2.url(:original)%>
      </li>
      <li class="" data-slide-to="2" data-target="#article-photo-carousel">
        <%= image_tag @kost.kost_img3.url(:original)%>
      </li>
    </ol>
  </div>


  <div class="show-informasi">
    <h3><%= @kost.nama_kos %></h3>
    <h4>Fasilitas</h4>
    <p><%= @kost.fasilitas %></p>
    <h4>Alamat</h4>
    <p><%= @kost.alamat %></p>
    <h4>Keterangan Lain</h4>
    <p><%= @kost.keterangan_lain %></p>
    <h3>IDR <%= @kost.harga_kos %></h3>
    <div class="box-pesan">
      <p style="border:none; padding:10px;">
        <%= link_to 'TANYAKAN', {controller: 'messages', action:'new', :received => @kost.pengguna_id, :param_id_kos => @kost.id }, class: 'btn-pesan' %>
      </p>
    </div>
  </div>
</div>

<br/>
<br/>
</br/>
<%= render 'footer'%>