config/routes.rb
Rails.application.routes.draw do
  get 'images/index'

  get 'images/create'

  devise_for :penggunas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'home#index'
  get '/', to: 'home#index'
  get '/tes', to: 'home#tes'
  get '/detail', to: 'kosts#detail'
  get '/inbox', to: 'kosts#inbox'
  get '/outbox', to: 'kosts#outbox'
  resources :kosts
  resources :messages
  resources :images, only: [:index, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lapakos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<p class="navbar-text pull-right">
<% if pengguna_signed_in? %>
  Logged in as <strong><%= current_pengguna.email %></strong>.
<% else %>
  <%= link_to "Sign up", new_pengguna_registration_pat, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_pengguna_session_path, :class => 'navbar-link'  %>
<% end %>
</p>


<!DOCTYPE html>
<html>
  <head>
    <title>LapaKos Dashboard</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<!--menu dashboard-->
  	<section id="menu-dashboard">

  	<div id="foto-profil-wrapper">
      <%= image_tag current_pengguna.avatar.url(:thumb), class: "foto-profil"%>
  	</div>

  		<ul>
		  <li><%= link_to "Kelola Kosan", {controller: 'kosts', action:'index'} %></li>
      <li><%= link_to 'Tambah Kosan', {controller: 'kosts', action:'new'} %></li>
		  <li><%= link_to 'Inbox', {controller: 'kosts', action:'inbox'} %></li>
      <li><%= link_to "Outbox", {controller: 'kosts', action:'outbox'} %></li>
      <li><%= link_to 'Edit profil', edit_pengguna_registration_path %></li>
      <li><%= link_to "Logout", destroy_pengguna_session_path, :method => :delete %></li>
		</ul>

    <div class="logo-white">
      <%= image_tag("logowhite.png", :alt => "logo lapakos", :class => "logo-dahboard") %>
    </div>

  	</section>
  	<!-- end of menu dashboard-->

  	<!--content dashboard -->
  	<section id="content-dashboard">
  		<%= yield %>
    </section>
    <!--end of content dashboard -->
  </body>
</html>